[project]
name = "connection-mapper"
version = "0.1.0"
description = "Connection Mapper captures traffic and visualises the devices your device connects to while its running"
authors = [
    {name = "Sam",email = "seriousemail178@gmail.com"}
]
license = "GPL-3.0"
license-files = ["LICENSE"]
requires-python = ">=3.12,<3.14.1 || >3.14.1,<3.15"
readme="README.md"
dependencies = [
    "scapy (>=2.7.0,<3.0.0)",
    "networkx (>=3.6.1,<4.0.0)",
    "pyqt6 (>=6.10.2,<7.0.0)",
    "numpy (>=2.4.2,<3.0.0)"
]

[tool.poetry]
packages = [
  { include = "connection_mapper", from = "src" },
  { include = "connection_mapper_gui", from = "src" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

